### PR TITLE
Update WEBHOOKS.md

### PR DESCRIPTION
**Pull request by Cat121**
Added reference to commands documentation

### CODE REVIEW

**Comment by Valandur** [comment]
Sorry for not merging this sooner. Thank you very much for getting it done!

**Comment by Valandur** [comment]
Can you change this to merge into develop, instead of directly into master? Sorry for not noticing that sooner :(

**Comment by Cat121** [comment]
Well honnestly I have no idea how to do :x

[image: Images intégrées 1]

2017-11-06 10:11 GMT+01:00 Marco (Valandur) <notifications@github.com>:

**Comment by Valandur** [comment]
I added this with one of my latest commits and mentioned you as a contributor. Thank you very much 👍

**Pull request closed without merging**
